/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace/account'
import { Route as WorkspaceJobsRouteImport } from './routes/_workspace/jobs'
import { Route as WorkspaceLearningRouteImport } from './routes/_workspace/learning'
import { Route as WorkspaceScreenRouteImport } from './routes/_workspace/screen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRouteRoute,
} as any).lazy(() =>
  import('./routes/_workspace/account.lazy').then((d) => d.Route),
)
const WorkspaceJobsRoute = WorkspaceJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => WorkspaceRouteRoute,
} as any).lazy(() =>
  import('./routes/_workspace/jobs.lazy').then((d) => d.Route),
)
const WorkspaceLearningRoute = WorkspaceLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => WorkspaceRouteRoute,
} as any).lazy(() =>
  import('./routes/_workspace/learning.lazy').then((d) => d.Route),
)
const WorkspaceScreenRoute = WorkspaceScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => WorkspaceRouteRoute,
} as any).lazy(() =>
  import('./routes/_workspace/screen.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/account': typeof WorkspaceAccountRoute
  '/jobs': typeof WorkspaceJobsRoute
  '/learning': typeof WorkspaceLearningRoute
  '/screen': typeof WorkspaceScreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/account': typeof WorkspaceAccountRoute
  '/jobs': typeof WorkspaceJobsRoute
  '/learning': typeof WorkspaceLearningRoute
  '/screen': typeof WorkspaceScreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/_workspace/jobs': typeof WorkspaceJobsRoute
  '/_workspace/learning': typeof WorkspaceLearningRoute
  '/_workspace/screen': typeof WorkspaceScreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/account' | '/jobs' | '/learning' | '/screen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/account' | '/jobs' | '/learning' | '/screen'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/account'
    | '/_workspace/jobs'
    | '/_workspace/learning'
    | '/_workspace/screen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/jobs': {
      id: '/_workspace/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof WorkspaceJobsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/learning': {
      id: '/_workspace/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof WorkspaceLearningRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/screen': {
      id: '/_workspace/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof WorkspaceScreenRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
  WorkspaceJobsRoute: typeof WorkspaceJobsRoute
  WorkspaceLearningRoute: typeof WorkspaceLearningRoute
  WorkspaceScreenRoute: typeof WorkspaceScreenRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAccountRoute: WorkspaceAccountRoute,
  WorkspaceJobsRoute: WorkspaceJobsRoute,
  WorkspaceLearningRoute: WorkspaceLearningRoute,
  WorkspaceScreenRoute: WorkspaceScreenRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
