/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace/account'
import { Route as ScreenSessionIdRouteImport } from './routes/screen.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/screen.lazy').then((d) => d.Route))
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRouteRoute,
} as any).lazy(() =>
  import('./routes/_workspace/account.lazy').then((d) => d.Route),
)
const ScreenSessionIdRoute = ScreenSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ScreenRoute,
} as any).lazy(() =>
  import('./routes/screen.$sessionId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/screen': typeof ScreenRouteWithChildren
  '/account': typeof WorkspaceAccountRoute
  '/screen/$sessionId': typeof ScreenSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/screen': typeof ScreenRouteWithChildren
  '/account': typeof WorkspaceAccountRoute
  '/screen/$sessionId': typeof ScreenSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/screen': typeof ScreenRouteWithChildren
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/screen/$sessionId': typeof ScreenSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/screen' | '/account' | '/screen/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/screen' | '/account' | '/screen/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/screen'
    | '/_workspace/account'
    | '/screen/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  ScreenRoute: typeof ScreenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/screen/$sessionId': {
      id: '/screen/$sessionId'
      path: '/$sessionId'
      fullPath: '/screen/$sessionId'
      preLoaderRoute: typeof ScreenSessionIdRouteImport
      parentRoute: typeof ScreenRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAccountRoute: WorkspaceAccountRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface ScreenRouteChildren {
  ScreenSessionIdRoute: typeof ScreenSessionIdRoute
}

const ScreenRouteChildren: ScreenRouteChildren = {
  ScreenSessionIdRoute: ScreenSessionIdRoute,
}

const ScreenRouteWithChildren =
  ScreenRoute._addFileChildren(ScreenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  ScreenRoute: ScreenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
